image: node:18

stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -y wget gnupg2 unzip
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - apt install -y ./google-chrome-stable_current_amd64.deb
  - rm google-chrome-stable_current_amd64.deb
  - wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/bin/chromedriver
  - chmod +x /usr/bin/chromedriver
  - npm install

test:
  stage: test
  script:
    - Xvfb :99 &
    - export DISPLAY=:99
    - yarn install
    - node webship-init -ci github -os linux -b chrome
    - yarn test
