default:
  image: node:16

stages:
  - deploy
  - confidence-check

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - yarn install
    - yarn run confidence-check --host=selenium__standalone-chrome
    - yarn test