default:
  image: node:16

stages:
  - deploy
  - confidence-check
deploy_terraform:
  stage: deploy
  script:
    # Your Review App deployment scripts - for a working example please check https://gitlab.com/Flockademic/Flockademic/blob/5a45f1c2412e93810fab50e2dab8949e2d0633c7/.gitlab-ci.yml#L315
    - echo
  environment: production
  
e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - yarn install
    - yarn add webdriverio --dev
    - yarn add -D @wdio/cli
    - yarn run confidence-check --host=selenium__standalone-chrome
    - yarn test