default:
  image: node:16

stages:
  - deploy
  - confidence-check

deploy_terraform:
  stage: deploy
  script:
    - echo
  environment: production

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - yarn install
    - yarn run --host=selenium__standalone-chrome
    - yarn test