default:
  image: node:18

stages:
  - test

serenity:
  stage: test
  image: node:lts
  services:
    - selenium/standalone-chrome
  script:
    - apt-get update && apt-get install default-jre -y
    - npm ci

    # configure your tests to use Selenium Grid at
    # selenium__standalone-chrome:4444
    - npm test
  artifacts:
    when: always
    paths:
      - target
      
test:
  script:
    - yarn install
    - yarn test