image: node:18

stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -yqq libnss3 libgconf-2-4 xvfb
  - npm install
  - wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.1.0/selenium-server-4.1.2.jar
  - java -jar selenium-server-4.1.2.jar standalone

test:
  stage: test
  script:
    - Xvfb :99 &
    - export DISPLAY=:99
    - yarn install
    - yarn test
