default:
  image: node:18

stages:
  - test

test:
  stage: test
  script:
    - apt-get update && apt-get install -y libnss3 libgconf-2-4
    - apt-get install -y default-jdk
    - npm install
    - Xvfb :99 &
    - export DISPLAY=:99
    - yarn install
    - yarn test
