image: node:18

stages:
  - test

before_script:
  - apt-get update -qq
  - apt-get install -yqq libnss3 libgconf-2-4 xvfb
  - npm install
  - npm install selenium-webdriver --save-dev
  - java -jar selenium-server-standalone-{VERSION}.jar

test:
  stage: test
  script:
    - Xvfb :99 &
    - export DISPLAY=:99
    - yarn install
    - yarn test
