module.exports.command = function () {
  return browser.url()
                .assert.textContains('footer', "Contact")
                .assert.textContains('footer', "About us")
                .assert.textContains('footer', "Privacy")
                .assert.textContains('footer', "© Copyright 2023 Webship")
                .assert.textContains('footer', "Github")
                .assert.textContains('footer', "Gitlab")
                .assert.textContains('footer', "Bitbucket")
                .assert.textContains('footer', "Twitter")
                .assert.textContains('footer', "Linkedin")
                .assert.textContains('footer', "Youtube")
                .smartClickLink("Contact")
                .waitForElementPresent('body', 6000)
                .assert.textContains('.page-title', "Contact")
                .back()
                .smartClickLink("About us")
                .waitForElementPresent('body', 6000)
                .assert.textContains('.page-title', "About us")
                .back()
                .smartClickLink("Privacy")
                .waitForElementPresent('body', 6000)
                .assert.textContains('.page-title', "Privacy")
                .back();

}